### ISSUE TITLE
Curl Output

### ISSUE THREAD

**Issue by idkjs** [tachyons-css/tachyons-generator#57]
What is this supposed to do? Nothing seems to happen after the re
```
$ curl -X POST \
→      -H "Content-Type: application/json" \
→      -d '{"typeScale": [5,4,3,2,1,0.5] }' \
→      https://tachyons.pub

<!doctype html>
<!-- https://now.sh -->
<h1>Redirecting (302)</h1>
<a href="https://zeit.co/johno/tachyons-publish-api/bvyenznlao?redirect=1">https://zeit.co/johno/tachyons-publish-api/bvyenznlao?redirect=1 </a>
```

**Comment by johnotander** [comment]
I think the server might've never unfrozen after Zeit now's outage on Friday. I just gave the server a kick so it should be working again. Could you give it another try and let me know if it continues to not work?

**Comment by idkjs** [comment]
Ok. Returns a url. https://s3-us-west-1.amazonaws.com/tachyons-pub/0.13.0/111e6389b4cc3b97dd4f2dcf07693226/index.html. So what just happened? I missed the magic i think. What is this doing exactly?

**Comment by johnotander** [comment]
Apologies that none of this is documented yet. It's pretty alpha software since I haven't had the time to formalize it after completing this proof of concept (that's nearly ready for a true beta aside from the lack of docs).

This project is the result of a couple hack sessions with the end goal of dynamically generating Tachyons css from a configuration. Hypothetically this allows (will allow) someone to generate their own custom project with different media queries, colors, typescales etc. with accompanying documentation.

The api itself provides a microservice that allows someone to make an api request to generate and host the docs/css in an S3 bucket. So, you can come up with your own configuration (a structured JSON object) and then POST it to the endpoint.

**Comment by idkjs** [comment]
Take a look at compositor.io. seems they are basically doing the same thing to generate a github static site...
